### ISSUE TITLE
[São Paulo] Dev Flutter | Ewally

### ISSUE THREAD

**Issue by MSimone12** [Flutterando/Vagas#3]
## About us:

Ewally is a Brazilian fintech based in São Paulo. Our mission is to make life easier for people and companies with limited access to financial services. We provide technological solutions to the unbanked population generating financial inclusion and high social-economic impact. 

We have an app that offers all the functionality one needs from a bank, in a full digital experience. We also provide services for big companies in the form of a BaaS (Bank as a Service) platform which offers all of our functionalities in the form of APIs.

At Ewally we make highly technological solutions to hard problems, so we strive for excellence in everything that we do. We are a highly motivated team and believe in autonomy and responsibility.

## About this role:

We are expanding our team and are currently looking for new app developers. This is a full time role based in our São Paulo Office (Avenida Angélica, 2529).** You can apply to any professional level and your application will be evaluated accordingly. **

As a Flutter developer you will have the opportunity to be involved with any aspect of an app lifecycle that you are interested in. We work in sprints using scrum and integrated teams and we believe in a simple, focused and transparent work environment. You will work with other developers, designers, product managers and an international list of partners and customers 

Our stack: We write both native and hybrid code and use the BLoC pattern for our Flutter apps. We also write a lot of code tests, have a full CI/CD pipeline and practice a DevOps approach.

## Things you'll do:

-   Design and implement apps in Flutter: a cutting-edge technology do develop fast and beautiful apps that work on all devices
-   Work with our design team to create the best user experience
-   Help to verify, test and monitor code to ensure the quality of our products
-   Interact with the product team and clients to better understand requirements
-   Study and learn bleeding edge technologies and use them to improve our systems and processes

## What we are looking for:

-   Desire to learn Flutter and Dart development
-   Knowledge in mobile development
-   Knowledge in webservices (consuming API, REST API)
-   Knowledge in development tools (terminal, git, etc..)

## Desireable skills:

-   Knowledge in information security
-   Knowledge in UI construction and design best pratices
-   Knowledge of best code pratices, like TDD, Clean Code
-   Knowledge in CI/CD and process automation

## We will like you if:

-   You always do what is right even if nobody is watching you 
-   You know that your work will never be perfect but you do care for the details
-   You are passionate about learning and like to share that learning with others
-   Solving real world problems and providing value to other people is what really motivates you
-   You enjoy being in a situation where you don’t know the answer, and are driven to try and figure it out
-   You accept critical feedback and provide constructive input to others

**Comment by AlvaroVasconcelos** [comment]
Please add a contact type.
