### ISSUE TITLE
Desenvolvedor Flutter Sênior

### ISSUE THREAD

**Issue by GiuliaProsdocimi** [Flutterando/Vagas#41]
# Informações importantes
Para que as vagas enviadas neste mural sejam categorizadas com as labels, as mesmas devem seguir as seguintes regras:
1. Vagas que violem o Código de Conduta serão automaticamente editadas e encerradas pela equipe de moderação.
2. Procure utilizar termos e descrições que façam o mínimo de distinção de gênero. Por exemplo, utilize "Desenvolvedor(a)", "Programador ou Programadora" ou "Pessoa".
3. Adicione links ou descreva as políticas de inclusão, não discriminação e afins adotadas pela empresa.
4. As vagas enviadas neste mural serão automaticamente divulgadas no canal do telegram da comunidade.
5. Remova este bloco inicial antes de divulgar a vaga.

## Descrição da vaga
Desenvolvimento em ambiente flutter. 

## Local

Remoto 

## Benefícios

- Bônus de 3-10 salários por performance semestral.
- VR/VA: R$1200

## Requisitos
- Arquitetura em MVVM, MVP ou MVC
- Integração em API rest
- Met Agil em Scrum ou Kanban
- Banco não relacional
- Testes TDD

Obrigatórios
- 6+ anos de experiência com Flutter

## Contratação

CLT 9k 

## Como se candidatar

Por favor envie um email para giulia.prosdocimi@uds.com.br com seu CV anexado - enviar no assunto: Vaga Flutter

**Comment by moreiralucas** [comment]
Fiquei curioso, como ter +6 anos de experiência com flutter se a primeira versão estável foi lançada em [04/12/2018](https://flutter.dev/docs/development/tools/sdk/releases)?

**Comment by krysthianlessa** [comment]
![flutter2](https://user-images.githubusercontent.com/14595398/117351723-6a768380-ae84-11eb-8c63-871c61e4858f.png)

**Comment by klausgreiner** [comment]
Perai isso é uma vaga séria? A pessoa nem seu deu o trabalho de modificar o texto direito. Ta com texto default nas informações importantes.
